version: '3.8'
services:
  db:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
    volumes:
      - db-data:/data:/var/lib/mysql
  backend:
    container_name: axum_server
    build:
      context: ./backend/
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/
volumes:
  db-data:
